#!/bin/bash

bright_folder=$(ls /sys/class/backlight | head -n 1)
bright_path="/sys/class/backlight/"$bright_folder"/brightness"
echo $bright_path

bright_val=$(cat $bright_path)
echo $bright_val

new_bright_val=$(($bright_val $1))

sudo chmod 766 $bright_path

echo $new_bright_val > $bright_path
