#!/bin/sh

# bright_val=$(cat /sys/class/backlight/amdgpu_bl0/max_brightness)

bright_folder=$(ls /sys/class/backlight | head -n 1)

sudo chmod 766 /sys/class/backlight/$bright_folder/brightness
echo 5 > /sys/class/backlight/$bright_folder/brightness
