#!/bin/bash
# autorandrState=$(autorandr | awk '{print $1}')
# if [[ $autorandrState == "docked" ]] || [[ $autorandrState == "mobile" ]]
# then 
#     autorandr -l docked
# else
#     autorandr -l mobile --force 
# fi

sleep 2
 if [[ $(mons | awk 'FNR==1 {print $2}')  == 1 ]]
 then
     echo "single monitor"
 	 /home/shaw/.screenlayout/mobile.sh
 else
     echo "dual monitor"
 	 /home/shaw/.screenlayout/docked.sh
 fi
